name: docker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:

  build:

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'docker build')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/ropensci-review-tools/pkgmatch-ollama:latest
