on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 1

name: Update pkgmatch data

jobs:

  update-pkgmatch-data:

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'update data')

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install this package
        run: R CMD INSTALL .

      - name: ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull jina/jina-embeddings-v2-base-en
          ollama pull ordis/jina-embeddings-v2-base-code
